In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("nba_games.csv",index_col = 0)

In [6]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
mp,,,,,,,,,,,,,,,,,,,,,
240.0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False
240.0,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,True
240.0,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
240.0,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
240.0,240.0,46.0,90.0,0.511,14.0,35.0,0.400,15.0,18.0,0.833,...,33.3,39.2,203.0,126.0,BOS,122,1,2021,2020-12-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240.0,240.0,42.0,96.0,0.438,15.0,42.0,0.357,10.0,21.0,0.476,...,63.5,29.7,115.0,127.0,LAL,81,0,2025,2025-04-13,True
240.0,240.0,40.0,84.0,0.476,15.0,44.0,0.341,3.0,6.0,0.500,...,50.0,31.1,169.0,118.0,SAC,109,1,2025,2025-04-13,False
240.0,240.0,46.0,88.0,0.523,14.0,34.0,0.412,3.0,3.0,1.000,...,30.0,34.7,135.0,128.0,PHO,98,0,2025,2025-04-13,True
240.0,240.0,46.0,97.0,0.474,14.0,39.0,0.359,12.0,16.0,0.750,...,30.7,29.2,230.0,124.0,SAS,125,1,2025,2025-04-13,False
240.0,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,18.9,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True

In [7]:
df = df.sort_values("date")

In [8]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
mp,,,,,,,,,,,,,,,,,,,,,
240.0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False
240.0,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,True
240.0,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
240.0,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
240.0,240.0,38.0,89.0,0.427,14.0,46.0,0.304,9.0,12.0,0.750,...,100.0,32.9,160.0,106.0,NOP,113,0,2021,2020-12-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
240.0,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,40.0,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False
240.0,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,31.6,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True
240.0,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,35.5,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False
240.0,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,25.8,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True
240.0,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,18.9,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True

In [9]:
df = df.reset_index(drop=True)

In [10]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,True
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,38.0,89.0,0.427,14.0,46.0,0.304,9.0,12.0,0.750,...,100.0,32.9,160.0,106.0,NOP,113,0,2021,2020-12-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,40.0,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False
12680,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,31.6,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True
12681,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,35.5,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False
12682,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,25.8,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True
12683,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,18.9,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True

In [11]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,True
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,38.0,89.0,0.427,14.0,46.0,0.304,9.0,12.0,0.750,...,100.0,32.9,160.0,106.0,NOP,113,0,2021,2020-12-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,40.0,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False
12680,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,31.6,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True
12681,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,35.5,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False
12682,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,25.8,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True
12683,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,18.9,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True

In [12]:
del df["mp_opp.1"]

In [13]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,43.6,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,50.0,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,True
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,100.0,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,20.9,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False
4,240.0,38.0,89.0,0.427,14.0,46.0,0.304,9.0,12.0,0.750,...,100.0,32.9,160.0,106.0,NOP,113,0,2021,2020-12-23,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,40.0,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False
12680,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,31.6,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True
12681,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,35.5,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False
12682,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,25.8,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True
12683,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,18.9,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True

In [14]:
#since we want to predict what team is going to win next game
def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team
#split data frame by teams
df = df.groupby("team",group_keys = False).apply(add_target)

C:\Users\peter\AppData\Local\Temp\ipykernel_19492\4226449861.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("team",group_keys = False).apply(add_target)

In [15]:
df[df["team"] == "GSW"]

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False,False
29,240.0,34.0,99.0,0.343,10.0,45.0,0.222,21.0,25.0,0.840,...,34.3,192.0,102.0,MIL,138,1,2021,2020-12-25,False,True
76,240.0,42.0,104.0,0.404,18.0,47.0,0.383,27.0,30.0,0.900,...,37.9,150.0,119.0,CHI,128,1,2021,2020-12-27,True,True
102,240.0,38.0,76.0,0.500,14.0,33.0,0.424,26.0,36.0,0.722,...,31.7,218.0,121.0,DET,106,1,2021,2020-12-29,True,False
134,240.0,31.0,79.0,0.392,7.0,35.0,0.200,29.0,33.0,0.879,...,29.0,250.0,102.0,POR,123,0,2021,2021-01-01,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12556,240.0,37.0,89.0,0.416,16.0,43.0,0.372,6.0,11.0,0.545,...,37.0,175.0,113.0,HOU,106,0,2025,2025-04-06,False,True
12575,240.0,45.0,93.0,0.484,15.0,40.0,0.375,28.0,34.0,0.824,...,35.8,183.0,140.0,PHO,95,1,2025,2025-04-08,True,False
12607,240.0,36.0,86.0,0.419,16.0,48.0,0.333,23.0,28.0,0.821,...,29.5,176.0,126.0,SAS,114,0,2025,2025-04-09,False,True
12630,240.0,33.0,83.0,0.398,14.0,44.0,0.318,23.0,28.0,0.821,...,29.7,127.0,112.0,POR,86,1,2025,2025-04-11,True,False
12672,265.0,43.0,79.0,0.544,15.0,33.0,0.455,18.0,23.0,0.783,...,32.8,205.0,126.0,LAC,124,0,2025,2025-04-13,False,NaN

In [16]:
df["target"][pd.isnull(df["target"])] = 2

C:\Users\peter\AppData\Local\Temp\ipykernel_19492\1618397414.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["target"][pd.isnull(df["target"])] = 2
C:\Users\peter\AppData\Local\Temp\ipykernel_19492\1618397414.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [17]:
df["target"] = df["target"].astype(int, errors="ignore")

In [18]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False,0
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,True,1
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True,1
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False,1
4,240.0,38.0,89.0,0.427,14.0,46.0,0.304,9.0,12.0,0.750,...,32.9,160.0,106.0,NOP,113,0,2021,2020-12-23,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False,2
12680,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True,2
12681,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False,2
12682,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True,2
12683,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True,2

In [19]:
df["won"].value_counts()

won
False    6342
True     6342
Name: count, dtype: int64

In [20]:
df["target"].value_counts()

target
0    6327
1    6327
2      30
Name: count, dtype: int64

In [21]:
#checkign how many columns are null since we need to remove them 
nulls = pd.isnull(df)

In [22]:
nulls

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12680,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12681,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12682,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12683,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [23]:
nulls.sum()

mp.1        0
fg          0
fga         0
fg%         0
3p          0
           ..
home_opp    0
season      0
date        0
won         0
target      0
Length: 152, dtype: int64

In [24]:
nulls[nulls > 0]

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
nulls = nulls[nulls > 0]

In [26]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [27]:
valid_columns

Index(['mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=152)

In [28]:
df = df[valid_columns].copy()

In [29]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,37.0,99.0,0.374,10.0,33.0,0.303,15.0,23.0,0.652,...,40.4,300.0,98.0,BRK,125,1,2021,2020-12-22,False,0
1,240.0,42.0,92.0,0.457,15.0,35.0,0.429,26.0,32.0,0.813,...,32.1,267.0,120.0,GSW,99,0,2021,2020-12-22,True,1
2,240.0,44.0,93.0,0.473,14.0,40.0,0.350,14.0,19.0,0.737,...,35.9,166.0,118.0,LAL,109,1,2021,2020-12-22,True,1
3,240.0,38.0,81.0,0.469,9.0,29.0,0.310,24.0,31.0,0.774,...,40.2,154.0,114.0,LAC,116,0,2021,2020-12-22,False,1
4,240.0,38.0,89.0,0.427,14.0,46.0,0.304,9.0,12.0,0.750,...,32.9,160.0,106.0,NOP,113,0,2021,2020-12-23,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,240.0,32.0,85.0,0.376,11.0,39.0,0.282,11.0,18.0,0.611,...,34.3,157.0,107.0,BOS,93,1,2025,2025-04-13,False,2
12680,240.0,47.0,88.0,0.534,17.0,40.0,0.425,6.0,10.0,0.600,...,33.6,191.0,129.0,ORL,105,0,2025,2025-04-13,True,2
12681,240.0,40.0,88.0,0.455,15.0,35.0,0.429,10.0,15.0,0.667,...,32.5,160.0,117.0,ATL,117,1,2025,2025-04-13,False,2
12682,240.0,52.0,104.0,0.500,15.0,41.0,0.366,13.0,15.0,0.867,...,31.7,143.0,137.0,DAL,97,0,2025,2025-04-13,True,2
12683,240.0,43.0,84.0,0.512,11.0,32.0,0.344,28.0,32.0,0.875,...,32.3,230.0,131.0,TOR,118,0,2025,2025-04-13,True,2

In [30]:
sanity = pd.isnull(df)

In [31]:
sanity

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12680,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12681,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12682,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12683,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
# 1. Find which columns have any NaN
nulls = df.isna().sum()
columns_with_nulls = nulls[nulls > 0].index

# 2. Keep only columns without NaN
valid_columns = df.columns[~df.columns.isin(columns_with_nulls)]
df = df[valid_columns].copy()

In [33]:
from sklearn.model_selection import TimeSeriesSplit
#need this so we can have past predicft future not the other way around

In [34]:
from sklearn.feature_selection import SequentialFeatureSelector

In [35]:
from sklearn.linear_model import RidgeClassifier

In [36]:
rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs=SequentialFeatureSelector(rr, n_features_to_select=30,direction="forward", cv=split)

In [37]:
# we need to scale the data for ridge regression... we are scaling are columns to fall between 0 and 1 
removed_columns = ["season","date","won","target","team","team_opp"]
#we are not scaling these columsn above
selected_columns = df.columns[~df.columns.isin(removed_columns)]
#we are scaling these collumns

In [38]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])

In [39]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.348837,0.614035,0.235437,0.296296,0.433962,0.380488,0.340909,0.433962,0.448276,...,0.235897,1.000000,0.200000,BRK,0.532110,1.0,2021,2020-12-22,False,0
1,0.0,0.465116,0.491228,0.436893,0.481481,0.471698,0.585366,0.590909,0.603774,0.448276,...,0.129487,0.833333,0.444444,GSW,0.293578,0.0,2021,2020-12-22,True,1
2,0.0,0.511628,0.508772,0.475728,0.444444,0.566038,0.456911,0.318182,0.358491,0.379310,...,0.178205,0.323232,0.422222,LAL,0.385321,1.0,2021,2020-12-22,True,1
3,0.0,0.372093,0.298246,0.466019,0.259259,0.358491,0.391870,0.545455,0.584906,0.275862,...,0.233333,0.262626,0.377778,LAC,0.449541,0.0,2021,2020-12-22,False,1
4,0.0,0.372093,0.438596,0.364078,0.444444,0.679245,0.382114,0.204545,0.226415,0.241379,...,0.139744,0.292929,0.288889,NOP,0.422018,0.0,2021,2020-12-23,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,0.0,0.232558,0.368421,0.240291,0.333333,0.547170,0.346341,0.250000,0.339623,0.620690,...,0.157692,0.277778,0.300000,BOS,0.238532,1.0,2025,2025-04-13,False,2
12680,0.0,0.581395,0.421053,0.623786,0.555556,0.566038,0.578862,0.136364,0.188679,0.310345,...,0.148718,0.449495,0.544444,ORL,0.348624,0.0,2025,2025-04-13,True,2
12681,0.0,0.418605,0.421053,0.432039,0.481481,0.471698,0.585366,0.227273,0.283019,0.413793,...,0.134615,0.292929,0.411111,ATL,0.458716,1.0,2025,2025-04-13,False,2
12682,0.0,0.697674,0.701754,0.541262,0.481481,0.584906,0.482927,0.295455,0.283019,0.655172,...,0.124359,0.207071,0.633333,DAL,0.275229,0.0,2025,2025-04-13,True,2
12683,0.0,0.488372,0.350877,0.570388,0.333333,0.415094,0.447154,0.636364,0.603774,0.310345,...,0.132051,0.646465,0.566667,TOR,0.467890,0.0,2025,2025-04-13,True,2

In [ ]:
sfs.fit(df[selected_columns],df["target"])

In [62]:
predictors = list(selected_columns[sfs.get_support()])
predictors

['fg%',
 'trb',
 '3par',
 'usg%',
 'ortg',
 'fta_max',
 'gmsc_max',
 'efg%_max',
 'ftr_max',
 'drb%_max',
 'stl%_max',
 'home',
 'orb_opp',
 'ast_opp',
 'pts_opp',
 'efg%_opp',
 'ast%_opp',
 'usg%_opp',
 'drtg_opp',
 'fga_max_opp',
 'orb_max_opp',
 'pf_max_opp',
 'gmsc_max_opp',
 'ftr_max_opp',
 'orb%_max_opp',
 'drb%_max_opp',
 'trb%_max_opp',
 'usg%_max_opp',
 'total_opp',
 'home_opp']

In [63]:
def backtest(data, model, predictors, start=2, step=1):
    #split data up by season and use past season to predicft future seasons
    all_predictions = []
    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"] < season]
        test = data[data["season"] == season]

        model.fit(train[predictors], train["target"])
        #training the model 

        preds = model.predict(test[predictors])
        #this is prediction the test set 
        preds = pd.Series(preds, index=test.index)
        combined = pd.concat([test["target"], preds], axis = 1)
        combined.columns = ["actual", "prediction"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [64]:
predictions = backtest(df, rr, predictors)

In [65]:
predictions

       actual  prediction
5214        1           0
5215        1           0
5229        1           0
5231        0           0
5232        1           0
...       ...         ...
12679       2           0
12680       2           1
12681       2           0
12682       2           1
12683       2           1

[6898 rows x 2 columns]

In [66]:
from sklearn.metrics import accuracy_score 
test = predictions[predictions["actual"] != 2]
accuracy_score(test["actual"], test["prediction"])
#calculating the accurary of are models

0.5564938846825859

In [67]:
df.iloc[12679]

IndexError: single positional indexer is out-of-bounds

In [68]:
df.loc[12683, ["team", "team_opp","date"]]

team               SAS
team_opp           TOR
date        2025-04-13
Name: 12683, dtype: object

In [69]:
df.groupby("home").apply(lambda x : x[x["won"] == 1].shape[0] / x.shape[0])

C:\Users\peter\AppData\Local\Temp\ipykernel_19492\2943530575.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby("home").apply(lambda x : x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.446347
1.0    0.552752
dtype: float64

In [70]:
df_rolling = df[list(selected_columns) + ["won", "team", "season"]]

In [71]:
df_rolling

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
250,0.0,0.372093,0.298246,0.466019,0.444444,0.396226,0.622764,0.454545,0.396226,0.137931,...,0.071,0.475891,0.121795,0.181818,0.400000,0.440367,1.0,False,BRK,2021
252,0.0,0.558140,0.473684,0.553398,0.296296,0.301887,0.513821,0.295455,0.264151,0.310345,...,0.159,0.184486,0.194872,0.323232,0.500000,0.458716,1.0,False,CHI,2021
253,0.0,0.441860,0.298246,0.555825,0.370370,0.358491,0.560976,0.522727,0.509434,0.344828,...,0.119,1.000000,0.134615,0.303030,0.544444,0.440367,0.0,True,LAL,2021
257,0.0,0.441860,0.385965,0.485437,0.370370,0.415094,0.497561,0.500000,0.566038,0.379310,...,0.129,0.509434,0.238462,0.631313,0.422222,0.366972,0.0,True,BOS,2021
261,0.0,0.418605,0.333333,0.497573,0.444444,0.396226,0.622764,0.250000,0.245283,0.344828,...,0.121,0.737945,0.160256,0.606061,0.422222,0.440367,1.0,False,LAC,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,0.0,0.232558,0.368421,0.240291,0.333333,0.547170,0.346341,0.250000,0.339623,0.620690,...,0.140,0.371069,0.157692,0.277778,0.300000,0.238532,1.0,False,CHO,2025
12680,0.0,0.581395,0.421053,0.623786,0.555556,0.566038,0.578862,0.136364,0.188679,0.310345,...,0.158,0.283019,0.148718,0.449495,0.544444,0.348624,0.0,True,ATL,2025
12681,0.0,0.418605,0.421053,0.432039,0.481481,0.471698,0.585366,0.227273,0.283019,0.413793,...,0.095,0.323899,0.134615,0.292929,0.411111,0.458716,1.0,False,ORL,2025
12682,0.0,0.697674,0.701754,0.541262,0.481481,0.584906,0.482927,0.295455,0.283019,0.655172,...,0.109,0.222222,0.124359,0.207071,0.633333,0.275229,0.0,True,MEM,2025
12683,0.0,0.488372,0.350877,0.570388,0.333333,0.415094,0.447154,0.636364,0.603774,0.310345,...,0.025,0.149895,0.132051,0.646465,0.566667,0.467890,0.0,True,SAS,2025

In [72]:
def find_team_average(team):
    #split df by team
    numeric_cols = team.select_dtypes(include='number')
    rolling = numeric_cols.rolling(10).mean() #group rows like 10 rows at a time using past 10 games to predict 
    return rolling

df_rolling = df_rolling.groupby(["team","season"],group_keys = False).apply(find_team_average)

C:\Users\peter\AppData\Local\Temp\ipykernel_19492\2820778389.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_rolling = df_rolling.groupby(["team","season"],group_keys = False).apply(find_team_average)

In [73]:
df_rolling

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,ast%_max_opp,stl%_max_opp,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,season
250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,0.0,0.348837,0.375439,0.386165,0.318519,0.458491,0.391870,0.352273,0.390566,0.362069,...,0.367213,0.0631,0.0940,0.328512,0.261154,0.451515,0.354444,0.449541,0.6,2025.0
12680,0.0,0.537209,0.461404,0.541748,0.500000,0.575472,0.507154,0.384091,0.409434,0.389655,...,0.274707,0.0607,0.0913,0.310063,0.174872,0.430808,0.554444,0.477982,0.6,2025.0
12681,0.0,0.413953,0.377193,0.456068,0.407407,0.490566,0.466829,0.361364,0.379245,0.379310,...,0.442623,0.1365,0.1054,0.384696,0.117436,0.412626,0.468889,0.315596,0.5,2025.0
12682,0.0,0.509302,0.491228,0.482767,0.511111,0.581132,0.520813,0.384091,0.392453,0.400000,...,0.318618,0.0527,0.0704,0.257757,0.183718,0.359091,0.518889,0.451376,0.6,2025.0
12683,0.0,0.439535,0.417544,0.461893,0.466667,0.558491,0.487154,0.334091,0.362264,0.303448,...,0.274941,0.0634,0.0769,0.389727,0.278333,0.530808,0.436667,0.479817,0.5,2025.0

In [87]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis =1 )

In [88]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,ast%_max_opp_10_10_10,stl%_max_opp_10_10_10,blk%_max_opp_10_10_10,tov%_max_opp_10_10_10,usg%_max_opp_10_10_10,ortg_max_opp_10_10_10,drtg_max_opp_10_10_10,total_opp_10_10_10,home_opp_10_10_10,season_10_10_10
486,0.0,0.279070,0.368421,0.298544,0.333333,0.528302,0.357724,0.431818,0.415094,0.206897,...,0.250937,0.0574,0.0892,0.385744,0.136282,0.405051,0.502222,0.475229,0.4,2021.0
496,0.0,0.325581,0.333333,0.381068,0.296296,0.320755,0.489431,0.272727,0.320755,0.310345,...,0.364169,0.0554,0.0996,0.436164,0.172051,0.515657,0.412222,0.334862,0.7,2021.0
498,0.0,0.441860,0.385965,0.485437,0.222222,0.264151,0.429268,0.363636,0.471698,0.206897,...,0.362412,0.0600,0.0900,0.398847,0.165641,0.441414,0.485556,0.336697,0.7,2021.0
499,0.0,0.441860,0.368421,0.497573,0.259259,0.283019,0.473171,0.363636,0.490566,0.241379,...,0.357260,0.0624,0.0856,0.331551,0.178718,0.327778,0.450000,0.421101,0.4,2021.0
506,0.0,0.418605,0.561404,0.339806,0.296296,0.301887,0.513821,0.386364,0.339623,0.586207,...,0.380445,0.1174,0.0818,0.462159,0.219744,0.409596,0.402222,0.414679,0.6,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.367213,0.0631,0.0940,0.328512,0.261154,0.451515,0.354444,0.449541,0.6,2025.0
12680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.274707,0.0607,0.0913,0.310063,0.174872,0.430808,0.554444,0.477982,0.6,2025.0
12681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.442623,0.1365,0.1054,0.384696,0.117436,0.412626,0.468889,0.315596,0.5,2025.0
12682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.318618,0.0527,0.0704,0.257757,0.183718,0.359091,0.518889,0.451376,0.6,2025.0
12683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.274941,0.0634,0.0769,0.389727,0.278333,0.530808,0.436667,0.479817,0.5,2025.0

In [89]:
df = df.dropna()

In [90]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,ast%_max_opp_10_10_10,stl%_max_opp_10_10_10,blk%_max_opp_10_10_10,tov%_max_opp_10_10_10,usg%_max_opp_10_10_10,ortg_max_opp_10_10_10,drtg_max_opp_10_10_10,total_opp_10_10_10,home_opp_10_10_10,season_10_10_10
486,0.0,0.279070,0.368421,0.298544,0.333333,0.528302,0.357724,0.431818,0.415094,0.206897,...,0.250937,0.0574,0.0892,0.385744,0.136282,0.405051,0.502222,0.475229,0.4,2021.0
496,0.0,0.325581,0.333333,0.381068,0.296296,0.320755,0.489431,0.272727,0.320755,0.310345,...,0.364169,0.0554,0.0996,0.436164,0.172051,0.515657,0.412222,0.334862,0.7,2021.0
498,0.0,0.441860,0.385965,0.485437,0.222222,0.264151,0.429268,0.363636,0.471698,0.206897,...,0.362412,0.0600,0.0900,0.398847,0.165641,0.441414,0.485556,0.336697,0.7,2021.0
499,0.0,0.441860,0.368421,0.497573,0.259259,0.283019,0.473171,0.363636,0.490566,0.241379,...,0.357260,0.0624,0.0856,0.331551,0.178718,0.327778,0.450000,0.421101,0.4,2021.0
506,0.0,0.418605,0.561404,0.339806,0.296296,0.301887,0.513821,0.386364,0.339623,0.586207,...,0.380445,0.1174,0.0818,0.462159,0.219744,0.409596,0.402222,0.414679,0.6,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12619,0.0,0.581395,0.315789,0.718447,0.222222,0.226415,0.479675,0.295455,0.339623,0.310345,...,0.329742,0.0484,0.0886,0.253354,0.168077,0.552525,0.530000,0.449541,0.4,2025.0
12620,0.0,0.465116,0.456140,0.461165,0.333333,0.452830,0.414634,0.250000,0.264151,0.379310,...,0.277049,0.0516,0.0770,0.439308,0.293205,0.464646,0.506667,0.386239,0.4,2025.0
12621,0.0,0.325581,0.456140,0.298544,0.740741,0.792453,0.575610,0.340909,0.415094,0.344828,...,0.419321,0.0565,0.0791,0.459644,0.192564,0.370707,0.370000,0.457798,0.3,2025.0
12622,0.0,0.604651,0.350877,0.713592,0.481481,0.490566,0.565854,0.500000,0.622642,0.241379,...,0.252225,0.0567,0.0826,0.301258,0.168077,0.430303,0.546667,0.500917,0.6,2025.0
12623,0.0,0.488372,0.596491,0.393204,0.555556,0.509434,0.634146,0.204545,0.245283,0.379310,...,0.261241,0.0730,0.0865,0.328826,0.133974,0.281818,0.547778,0.440367,0.5,2025.0

In [91]:
def shift_col(team, col_name):
    next_col = team[col_name].shift(-1)
    return next_col

def add_col(df,col_name):
    return df.groupby("team",group_keys = False).apply(lambda x: shift_col(x,col_name))

df["home_next"] = add_col(df, "home")

C:\Users\peter\AppData\Local\Temp\ipykernel_19492\3142859057.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team",group_keys = False).apply(lambda x: shift_col(x,col_name))
C:\Users\peter\AppData\Local\Temp\ipykernel_19492\3142859057.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["home_next"] = add_col(df, "home")

In [92]:
df["team_opp_next"] = add_col(df,"team_opp")
df["date_next"] = add_col(df, "date")

C:\Users\peter\AppData\Local\Temp\ipykernel_19492\3142859057.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team",group_keys = False).apply(lambda x: shift_col(x,col_name))
C:\Users\peter\AppData\Local\Temp\ipykernel_19492\1446644618.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["team_opp_next"] = add_col(df,"team_opp")
C:\Users\peter\AppData\Local\Temp\ipykernel_19492\3142859057.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby("team",group_keys = False).apply(lambda x: shift_col(x,col_name))
C:\Users\peter\AppData\Local\Temp\ipykernel_19492\1446644618.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["date_next"] = add_col(df, "date")

In [93]:
df

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,ast%_max_opp_10_10_10,stl%_max_opp_10_10_10,blk%_max_opp_10_10_10,tov%_max_opp_10_10_10,usg%_max_opp_10_10_10,ortg_max_opp_10_10_10,drtg_max_opp_10_10_10,total_opp_10_10_10,home_opp_10_10_10,season_10_10_10
486,0.0,0.279070,0.368421,0.298544,0.333333,0.528302,0.357724,0.431818,0.415094,0.206897,...,0.250937,0.0574,0.0892,0.385744,0.136282,0.405051,0.502222,0.475229,0.4,2021.0
496,0.0,0.325581,0.333333,0.381068,0.296296,0.320755,0.489431,0.272727,0.320755,0.310345,...,0.364169,0.0554,0.0996,0.436164,0.172051,0.515657,0.412222,0.334862,0.7,2021.0
498,0.0,0.441860,0.385965,0.485437,0.222222,0.264151,0.429268,0.363636,0.471698,0.206897,...,0.362412,0.0600,0.0900,0.398847,0.165641,0.441414,0.485556,0.336697,0.7,2021.0
499,0.0,0.441860,0.368421,0.497573,0.259259,0.283019,0.473171,0.363636,0.490566,0.241379,...,0.357260,0.0624,0.0856,0.331551,0.178718,0.327778,0.450000,0.421101,0.4,2021.0
506,0.0,0.418605,0.561404,0.339806,0.296296,0.301887,0.513821,0.386364,0.339623,0.586207,...,0.380445,0.1174,0.0818,0.462159,0.219744,0.409596,0.402222,0.414679,0.6,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12619,0.0,0.581395,0.315789,0.718447,0.222222,0.226415,0.479675,0.295455,0.339623,0.310345,...,0.329742,0.0484,0.0886,0.253354,0.168077,0.552525,0.530000,0.449541,0.4,2025.0
12620,0.0,0.465116,0.456140,0.461165,0.333333,0.452830,0.414634,0.250000,0.264151,0.379310,...,0.277049,0.0516,0.0770,0.439308,0.293205,0.464646,0.506667,0.386239,0.4,2025.0
12621,0.0,0.325581,0.456140,0.298544,0.740741,0.792453,0.575610,0.340909,0.415094,0.344828,...,0.419321,0.0565,0.0791,0.459644,0.192564,0.370707,0.370000,0.457798,0.3,2025.0
12622,0.0,0.604651,0.350877,0.713592,0.481481,0.490566,0.565854,0.500000,0.622642,0.241379,...,0.252225,0.0567,0.0826,0.301258,0.168077,0.430303,0.546667,0.500917,0.6,2025.0
12623,0.0,0.488372,0.596491,0.393204,0.555556,0.509434,0.634146,0.204545,0.245283,0.379310,...,0.261241,0.0730,0.0865,0.328826,0.133974,0.281818,0.547778,0.440367,0.5,2025.0

In [94]:
df = df.copy()

In [95]:
full = df.merge(df[rolling_cols + ["team_opp_next","date_next","team"]], 
                left_on =["team","date_next"], right_on = ["team_opp_next","date_next"])

In [99]:
full

,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,orb,...,blk%_max_opp_10_10_10_y,tov%_max_opp_10_10_10_y,usg%_max_opp_10_10_10_y,ortg_max_opp_10_10_10_y,drtg_max_opp_10_10_10_y,total_opp_10_10_10_y,home_opp_10_10_10_y,season_10_10_10_y,team_opp_next_y,team_y
0,0.0,0.418605,0.561404,0.339806,0.296296,0.301887,0.513821,0.386364,0.339623,0.586207,...,0.0926,0.394130,0.160256,0.324747,0.521111,0.356881,0.4,2021.0,ORL,LAC
1,0.0,0.418605,0.403509,0.444175,0.444444,0.490566,0.520325,0.295455,0.245283,0.172414,...,0.1200,0.423166,0.090897,0.377273,0.401111,0.407339,0.4,2021.0,DET,GSW
2,0.0,0.325581,0.403509,0.332524,0.555556,0.603774,0.546341,0.454545,0.415094,0.448276,...,0.0818,0.462159,0.219744,0.409596,0.402222,0.414679,0.6,2021.0,LAC,ORL
3,0.0,0.372093,0.614035,0.259709,0.333333,0.528302,0.357724,0.136364,0.150943,0.413793,...,0.1019,0.342453,0.208333,0.432323,0.446667,0.373394,0.4,2021.0,GSW,DET
4,0.0,0.465116,0.385965,0.512136,0.407407,0.415094,0.547967,0.613636,0.622642,0.413793,...,0.0970,0.514570,0.221795,0.388889,0.393333,0.418349,0.5,2021.0,TOR,ORL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9803,0.0,0.348837,0.298246,0.436893,0.333333,0.528302,0.357724,0.340909,0.433962,0.206897,...,0.0787,0.356918,0.113846,0.412121,0.404444,0.404587,0.6,2025.0,CHO,TOR
9804,0.0,0.395349,0.315789,0.483010,0.370370,0.433962,0.479675,0.545455,0.584906,0.310345,...,0.0591,0.241090,0.148590,0.394949,0.515556,0.454128,0.6,2025.0,NOP,MIL
9805,0.0,0.674419,0.631579,0.565534,0.851852,0.754717,0.700813,0.181818,0.245283,0.551724,...,0.0658,0.366562,0.163590,0.485859,0.526667,0.374312,0.2,2025.0,CLE,IND
9806,0.0,0.255814,0.403509,0.247573,0.259259,0.471698,0.305691,0.659091,0.698113,0.448276,...,0.0860,0.357966,0.136538,0.308586,0.564444,0.456881,0.5,2025.0,IND,CLE
9807,0.0,0.441860,0.385965,0.485437,0.481481,0.622642,0.455285,0.363636,0.358491,0.413793,...,0.0808,0.354298,0.143974,0.395455,0.551111,0.333028,0.3,2025.0,CHI,MIA

In [105]:
full[["team_x", "team_opp_next_x", "team_y", "team_opp_next_y", "date_next"]]

     team_x team_opp_next_x team_y team_opp_next_y   date_next
0       ORL             LAC    LAC             ORL  2021-01-29
1       DET             GSW    GSW             DET  2021-01-30
2       LAC             ORL    ORL             LAC  2021-01-29
3       GSW             DET    DET             GSW  2021-01-30
4       TOR             ORL    ORL             TOR  2021-01-31
...     ...             ...    ...             ...         ...
9803    CHO             TOR    TOR             CHO  2025-04-09
9804    NOP             MIL    MIL             NOP  2025-04-10
9805    CLE             IND    IND             CLE  2025-04-10
9806    IND             CLE    CLE             IND  2025-04-10
9807    CHI             MIA    MIA             CHI  2025-04-09

[9808 rows x 5 columns]

In [106]:
removed_columns = list(full.columns[full.dtypes == "object"]) + removed_columns

In [107]:
removed_columns

['team_x',
 'team_opp',
 'date',
 'won',
 'team_opp_next_x',
 'date_next',
 'team_opp_next_y',
 'team_y',
 'season',
 'date',
 'won',
 'target',
 'team',
 'team_opp']

In [108]:
selected_columns = full.columns[~full.columns.isin(removed_columns)]

In [109]:
selected_columns

Index(['mp.1', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'orb',
       ...
       'ast%_max_opp_10_10_10_y', 'stl%_max_opp_10_10_10_y',
       'blk%_max_opp_10_10_10_y', 'tov%_max_opp_10_10_10_y',
       'usg%_max_opp_10_10_10_y', 'ortg_max_opp_10_10_10_y',
       'drtg_max_opp_10_10_10_y', 'total_opp_10_10_10_y',
       'home_opp_10_10_10_y', 'season_10_10_10_y'],
      dtype='object', length=798)

In [ ]:
sfs.fit(full[selected_columns], full["target"])

In [ ]:
predictors = list(selected_colum[sfs.get_support()])